### ISSUE TITLE
This is very similar to PayID

### ISSUE THREAD

**Issue by augustresende** [opencap/protocol#63]
This is very similar to PayID, https://github.com/payid-org/payid/

https://github.com/payid-org/payid/issues/540

**Comment by ThatBrianDude** [comment]
Thanks for the reference. Seems pretty much identical in how it works. 

I am in contact with the author of PayID and it seems the intention wasnt any other than to have a "new" solution for marketing reasons.

I have yet to find out why OpenCAP was turned down in favor of PayID on the technical side. It seems a bad decision to go for a brand new pretty much identical protocol and ignoring the adoption opencap received so far.

**Comment by augustresende** [comment]
Maybe it's possible to build an abstraction that supports both?

**Comment by ThatBrianDude** [comment]
Two alias systems with identical alias anatomy will conflict with eachother. What happens when I want to send funds to an address present in both systems? 

The thing is that PayID provides simply zero advantages over opencap on the technical side so the question is whether or not PayID deserves to be considered at all. (Still hard to comprehend why it exists in the first place as the author was loosely involved in opencap as well)
